# Generated by Django 4.2.13 on 2025-06-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturasensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturasensor',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturasensor',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
