# Generated by Django 4.2.13 on 2025-06-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='subsistema.subsitema')),
            ],
        ),
    ]
