# Generated by Django 4.2.13 on 2025-06-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('actuador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoActuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_activa', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], max_length=20)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='actuador.actuador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_actuador', to='users.usuario')),
            ],
        ),
    ]
